# Generated by Django 4.2.5 on 2023-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_title',
            field=models.CharField(default='new chat', max_length=500),
        ),
    ]
