# Generated by Django 4.2.5 on 2023-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_chat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='response',
        ),
        migrations.AddField(
            model_name='message',
            name='prompt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
