# Generated by Django 4.2.5 on 2023-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_content_message_response_message_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
