# Generated by Django 4.2.5 on 2023-09-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
