# Generated by Django 4.2.5 on 2023-09-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
